# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QLineEdit, QMainWindow, QMenu,
    QMenuBar, QPushButton, QSizePolicy, QSlider,
    QStatusBar, QTextBrowser, QWidget)

from Camera import Camera

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(700, 560)
        MainWindow.setMinimumSize(QSize(700, 560))
        MainWindow.setMaximumSize(QSize(700, 560))
        font = QFont()
        font.setFamilies([u"Segoe UI Semibold"])
        font.setPointSize(12)
        font.setBold(True)
        font.setKerning(True)
        MainWindow.setFont(font)
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionNew = QAction(MainWindow)
        self.actionNew.setObjectName(u"actionNew")
        self.actionRemove = QAction(MainWindow)
        self.actionRemove.setObjectName(u"actionRemove")
        self.actionWhy = QAction(MainWindow)
        self.actionWhy.setObjectName(u"actionWhy")
        self.actionDo = QAction(MainWindow)
        self.actionDo.setObjectName(u"actionDo")
        self.actionI = QAction(MainWindow)
        self.actionI.setObjectName(u"actionI")
        self.actionHate = QAction(MainWindow)
        self.actionHate.setObjectName(u"actionHate")
        self.actionMyself = QAction(MainWindow)
        self.actionMyself.setObjectName(u"actionMyself")
        self.action_Yes = QAction(MainWindow)
        self.action_Yes.setObjectName(u"action_Yes")
        self.action_Yes_2 = QAction(MainWindow)
        self.action_Yes_2.setObjectName(u"action_Yes_2")
        self.action_New = QAction(MainWindow)
        self.action_New.setObjectName(u"action_New")
        self.action_Open = QAction(MainWindow)
        self.action_Open.setObjectName(u"action_Open")
        self.action_Remove = QAction(MainWindow)
        self.action_Remove.setObjectName(u"action_Remove")
        self.actionChange_Camera = QAction(MainWindow)
        self.actionChange_Camera.setObjectName(u"actionChange_Camera")
        self.actionRemove_2 = QAction(MainWindow)
        self.actionRemove_2.setObjectName(u"actionRemove_2")
        self.actionOpen_2 = QAction(MainWindow)
        self.actionOpen_2.setObjectName(u"actionOpen_2")
        self.actionSelect = QAction(MainWindow)
        self.actionSelect.setObjectName(u"actionSelect")
        self.actionLoad = QAction(MainWindow)
        self.actionLoad.setObjectName(u"actionLoad")
        self.actionAdd_2 = QAction(MainWindow)
        self.actionAdd_2.setObjectName(u"actionAdd_2")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QSize(600, 500))
        self.centralwidget.setMaximumSize(QSize(800, 500))
        self.centralwidget.setBaseSize(QSize(1000, 800))
        palette = QPalette()
        brush = QBrush(QColor(63, 63, 63, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush)
        self.centralwidget.setPalette(palette)
        self.run_button = QPushButton(self.centralwidget)
        self.run_button.setObjectName(u"run_button")
        self.run_button.setGeometry(QRect(540, 430, 111, 51))
        palette1 = QPalette()
        brush1 = QBrush(QColor(49, 49, 49, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(255, 255, 255, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush2)
        brush3 = QBrush(QColor(70, 180, 127, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush3)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush3)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        self.run_button.setPalette(palette1)
        font1 = QFont()
        font1.setFamilies([u"Segoe UI Semibold"])
        font1.setPointSize(18)
        font1.setBold(True)
        font1.setUnderline(False)
        font1.setKerning(True)
        self.run_button.setFont(font1)
        self.confidence_slider = QSlider(self.centralwidget)
        self.confidence_slider.setObjectName(u"confidence_slider")
        self.confidence_slider.setGeometry(QRect(30, 430, 371, 61))
        font2 = QFont()
        font2.setFamilies([u"Segoe UI Semibold"])
        font2.setPointSize(12)
        font2.setBold(True)
        font2.setUnderline(False)
        font2.setKerning(True)
        self.confidence_slider.setFont(font2)
        self.confidence_slider.setMaximum(100)
        self.confidence_slider.setOrientation(Qt.Orientation.Horizontal)
        self.confidence_slider.setTickPosition(QSlider.TickPosition.TicksAbove)
        self.confidence_slider.setTickInterval(5)
        self.camera_output = Camera(self.centralwidget)
        self.camera_output.setObjectName(u"camera_output")
        self.camera_output.setGeometry(QRect(30, 20, 461, 391))
        self.textBrowser = QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName(u"textBrowser")
        self.textBrowser.setGeometry(QRect(510, 20, 171, 391))
        self.lineEdit = QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(410, 450, 81, 21))
        self.lineEdit.setClearButtonEnabled(False)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 700, 33))
        self.menubar.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.menubar.setAutoFillBackground(True)
        self.menuwhere_is_the_box = QMenu(self.menubar)
        self.menuwhere_is_the_box.setObjectName(u"menuwhere_is_the_box")
        self.menuCreate_New = QMenu(self.menuwhere_is_the_box)
        self.menuCreate_New.setObjectName(u"menuCreate_New")
        self.menuFrom_Folder = QMenu(self.menuCreate_New)
        self.menuFrom_Folder.setObjectName(u"menuFrom_Folder")
        self.menuDatasets = QMenu(self.menubar)
        self.menuDatasets.setObjectName(u"menuDatasets")
        self.menuAdd = QMenu(self.menuDatasets)
        self.menuAdd.setObjectName(u"menuAdd")
        self.menuAdd_To_Models = QMenu(self.menuAdd)
        self.menuAdd_To_Models.setObjectName(u"menuAdd_To_Models")
        self.menuModels = QMenu(self.menubar)
        self.menuModels.setObjectName(u"menuModels")
        self.menuGithub = QMenu(self.menubar)
        self.menuGithub.setObjectName(u"menuGithub")
        self.menuSave = QMenu(self.menubar)
        self.menuSave.setObjectName(u"menuSave")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuwhere_is_the_box.menuAction())
        self.menubar.addAction(self.menuDatasets.menuAction())
        self.menubar.addAction(self.menuModels.menuAction())
        self.menubar.addAction(self.menuGithub.menuAction())
        self.menubar.addAction(self.menuSave.menuAction())
        self.menuwhere_is_the_box.addAction(self.actionChange_Camera)
        self.menuwhere_is_the_box.addAction(self.menuCreate_New.menuAction())
        self.menuCreate_New.addAction(self.menuFrom_Folder.menuAction())
        self.menuFrom_Folder.addAction(self.actionSelect)
        self.menuDatasets.addAction(self.menuAdd.menuAction())
        self.menuDatasets.addAction(self.actionRemove_2)
        self.menuDatasets.addAction(self.actionOpen_2)
        self.menuAdd.addAction(self.menuAdd_To_Models.menuAction())
        self.menuAdd_To_Models.addAction(self.actionLoad)
        self.menuAdd_To_Models.addAction(self.actionAdd_2)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.actionNew.setText(QCoreApplication.translate("MainWindow", u"New", None))
        self.actionRemove.setText(QCoreApplication.translate("MainWindow", u"Remove", None))
        self.actionWhy.setText(QCoreApplication.translate("MainWindow", u"Why", None))
        self.actionDo.setText(QCoreApplication.translate("MainWindow", u"Do", None))
        self.actionI.setText(QCoreApplication.translate("MainWindow", u"I", None))
        self.actionHate.setText(QCoreApplication.translate("MainWindow", u"Hate", None))
        self.actionMyself.setText(QCoreApplication.translate("MainWindow", u"Myself", None))
        self.action_Yes.setText(QCoreApplication.translate("MainWindow", u"%Yes", None))
        self.action_Yes_2.setText(QCoreApplication.translate("MainWindow", u"&Yes", None))
        self.action_New.setText(QCoreApplication.translate("MainWindow", u"&New", None))
        self.action_Open.setText(QCoreApplication.translate("MainWindow", u"&Open", None))
        self.action_Remove.setText(QCoreApplication.translate("MainWindow", u"&Remove", None))
        self.actionChange_Camera.setText(QCoreApplication.translate("MainWindow", u"Change_Camera", None))
        self.actionRemove_2.setText(QCoreApplication.translate("MainWindow", u"Remove", None))
        self.actionOpen_2.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.actionSelect.setText(QCoreApplication.translate("MainWindow", u"Select", None))
        self.actionLoad.setText(QCoreApplication.translate("MainWindow", u"Load", None))
        self.actionAdd_2.setText(QCoreApplication.translate("MainWindow", u"Add", None))
        self.run_button.setText(QCoreApplication.translate("MainWindow", u"Run", None))
        self.lineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"percent", None))
        self.menuwhere_is_the_box.setTitle(QCoreApplication.translate("MainWindow", u"Tools", None))
        self.menuCreate_New.setTitle(QCoreApplication.translate("MainWindow", u"Create_New", None))
        self.menuFrom_Folder.setTitle(QCoreApplication.translate("MainWindow", u"From_Folder", None))
        self.menuDatasets.setTitle(QCoreApplication.translate("MainWindow", u"Datasets", None))
        self.menuAdd.setTitle(QCoreApplication.translate("MainWindow", u"Add", None))
        self.menuAdd_To_Models.setTitle(QCoreApplication.translate("MainWindow", u"Add_To_Models", None))
        self.menuModels.setTitle(QCoreApplication.translate("MainWindow", u"Models", None))
        self.menuGithub.setTitle(QCoreApplication.translate("MainWindow", u"Github", None))
        self.menuSave.setTitle(QCoreApplication.translate("MainWindow", u"Save", None))
    # retranslateUi

